server:
  session-timeout: 1800
bootdo:
  uploadPath: D:/var/uploaded_files/
logging:
  level:
    root: info
    com.bootdo: info
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://122.51.90.196:5559/yusp_bfp?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 111111


  redis:
    host: 122.51.90.196
    port: 6379
    password: d5gmwWgiV~5g
    #测试环境redis密码 igc)5huxZ4jK
    # 连接超时时间（毫秒）
    timeout: 10000
    pool:
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 10
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 100
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1



